# Generated by Django 2.2.24 on 2023-09-02 11:27

from django.db import migrations


def move_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(name=flat.owner,
                                    phonenumber=flat.owners_phonenumber,
                                    pure_phone=flat.owner_pure_phone)
        owner[0].flats.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230831_1835'),
    ]

    operations = [
        migrations.RunPython(move_flat)
    ]
